<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHY A SEAT HOLDS AN EXCEPTION TO A RULE: the reason a Super Admin wrote when
 * giving it, who gave it and when, and — once taken away — who took it and
 * when. At most one row in force per seat and pair. A new table; nothing to
 * backfill, since no exception existed before it.
 */
final class Version20260926000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_grant_justification';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE team_grant_justification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pair VARCHAR(120) NOT NULL, reason TEXT NOT NULL, granted_by_name VARCHAR(160) NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_by_name VARCHAR(160) DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position_id INT NOT NULL, granted_by_id INT DEFAULT NULL, revoked_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_127CE394DD842E46 ON team_grant_justification (position_id)');
        $this->addSql('CREATE INDEX IDX_127CE3943151C11F ON team_grant_justification (granted_by_id)');
        $this->addSql('CREATE INDEX IDX_127CE394FB8FE773 ON team_grant_justification (revoked_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_grant_justification_current ON team_grant_justification (position_id, pair) WHERE (revoked_at IS NULL)');
        $this->addSql('ALTER TABLE team_grant_justification ADD CONSTRAINT FK_127CE394DD842E46 FOREIGN KEY (position_id) REFERENCES team_position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_grant_justification ADD CONSTRAINT FK_127CE3943151C11F FOREIGN KEY (granted_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_grant_justification ADD CONSTRAINT FK_127CE394FB8FE773 FOREIGN KEY (revoked_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_grant_justification');
    }
}
