<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE AUDIT OF DELETES (ruled 28 Sep, #48): one line per delete a Super Admin
 * makes - who, what, when, and what went with it. Schema only: a new table.
 */
final class Version20260930140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_deletion';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE team_deletion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, by_name VARCHAR(160) NOT NULL, by_id INT DEFAULT NULL, kind VARCHAR(60) NOT NULL, reference VARCHAR(160) NOT NULL, title VARCHAR(255) NOT NULL, what_went TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_team_deletion_at ON team_deletion (deleted_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_deletion');
    }
}
