<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE ORGANIZATION'S RANKS — the scales, the ranks on each in seniority
 * order, and the rank each person holds with its history.
 *
 * ONE SCALE IS WRITTEN HERE, unnamed: an organization has one scale until it
 * adds a second, and nothing on a page names it until then.
 *
 * AND THE SWITCH, ON. "This organization uses ranks" is added to the one
 * settings row with its default in the same statement, so the row already
 * there reads on without a separate backfill.
 */
final class Version20260925000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_rank_scale with its one scale, team_rank, team_rank_holding, and team_settings.uses_ranks';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_rank_scale (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(80) DEFAULT NULL,
                sort_order INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                uuid UUID NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF9B18DCD17F50A6 ON team_rank_scale (uuid)');
        $this->addSql('INSERT INTO team_rank_scale (name, sort_order, created_at, updated_at, uuid) VALUES (NULL, 1, NOW(), NOW(), gen_random_uuid())');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_rank (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(120) NOT NULL,
                short_code VARCHAR(24) NOT NULL,
                seniority INT NOT NULL,
                retired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                uuid UUID NOT NULL,
                scale_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_59981C9ED17F50A6 ON team_rank (uuid)');
        $this->addSql('CREATE INDEX IDX_59981C9EF73142C2 ON team_rank (scale_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_rank_holding (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                since DATE NOT NULL,
                until DATE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                person_id INT NOT NULL,
                rank_id INT NOT NULL,
                recorded_by_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_71B55086217BBB47 ON team_rank_holding (person_id)');
        $this->addSql('CREATE INDEX IDX_71B550867616678F ON team_rank_holding (rank_id)');
        $this->addSql('CREATE INDEX IDX_71B55086D05A957B ON team_rank_holding (recorded_by_id)');

        $this->addSql('ALTER TABLE team_rank ADD CONSTRAINT FK_59981C9EF73142C2 FOREIGN KEY (scale_id) REFERENCES team_rank_scale (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_rank_holding ADD CONSTRAINT FK_71B55086217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_rank_holding ADD CONSTRAINT FK_71B550867616678F FOREIGN KEY (rank_id) REFERENCES team_rank (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_rank_holding ADD CONSTRAINT FK_71B55086D05A957B FOREIGN KEY (recorded_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('ALTER TABLE team_settings ADD uses_ranks BOOLEAN DEFAULT true NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_settings DROP uses_ranks');
        $this->addSql('DROP TABLE team_rank_holding');
        $this->addSql('DROP TABLE team_rank');
        $this->addSql('DROP TABLE team_rank_scale');
    }
}
