<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A ONE-TIME PASSWORD, ISSUED BY AN ADMINISTRATOR. A new table for the issues
 * (who, for whom, when, when first used) and one nullable column on the
 * account for a one-time password not yet used. Schema only: nothing existed
 * before it, so nothing is filled in.
 */
final class Version20260927220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_one_time_password, team_user.one_time_password_issued_at';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE team_one_time_password (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issued_by_name VARCHAR(160) NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, issued_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B780A78E217BBB47 ON team_one_time_password (person_id)');
        $this->addSql('CREATE INDEX IDX_B780A78E784BB717 ON team_one_time_password (issued_by_id)');
        $this->addSql('ALTER TABLE team_one_time_password ADD CONSTRAINT FK_B780A78E217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_one_time_password ADD CONSTRAINT FK_B780A78E784BB717 FOREIGN KEY (issued_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_user ADD one_time_password_issued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_user DROP one_time_password_issued_at');
        $this->addSql('DROP TABLE team_one_time_password');
    }
}
