<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\RegistryBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE QUEUE'S TABLE: `messenger_messages`, which the Doctrine transport of the
 * core's recipe (`async` and `failed`, one table, a queue name each) reads and
 * writes. The recipe's DSN carries `auto_setup=0`, so the transport never
 * creates it in a request; the schema is the migrations'. The statements are
 * the ones `doctrine:migrations:diff` writes for the transport's own schema
 * definition on PostgreSQL:
 *
 *   "For production: generate migration and create table explicitly"
 *   — https://symfony.com/doc/current/messenger.html#doctrine-transport
 *
 * @see vendor/symfony/doctrine-messenger/Transport/Connection.php — configureSchema() / addTableToSchema(), the table and its one index
 * @see vendor/symfony/doctrine-bridge/SchemaListener/MessengerTransportDoctrineSchemaListener.php — how the table enters the schema a diff compares
 *
 * IF NOT EXISTS because an installation whose transport already created the
 * table (auto_setup on, or `messenger:setup-transports`) has it, and this has
 * to bring it and a fresh installation to one schema. PostgreSQL's notify on a
 * new message is sent by the transport itself (`pg_notify`), so no trigger.
 */
final class Version20260925210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'messenger_messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
