<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\RegistryBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE SETTINGS STORE: one row per value Super Admins and Admins set in
 * Settings — the organization's for a setting (no place), or a custom one for
 * an area or a department (the place's uuid). Two partial unique indexes, as
 * the department's name: one organization value per setting, one custom value
 * per setting, level and place.
 *
 * A clean start (ruled 1 Oct 2026): nothing is copied in from the modules'
 * own settings tables; the values begin at their defaults.
 */
final class Version20261001000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'setting_value: the settings store';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE setting_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(120) NOT NULL, level VARCHAR(16) NOT NULL, place_uuid UUID DEFAULT NULL, value JSON NOT NULL, set_by VARCHAR(180) NOT NULL, set_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_setting_value_organization ON setting_value (setting_key) WHERE (place_uuid IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_setting_value_place ON setting_value (setting_key, level, place_uuid) WHERE (place_uuid IS NOT NULL)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE setting_value');
    }
}
